import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import type { CatalogEntry, Level } from "./uni-data";

/* ---------- Domain types ---------- */

/**
 * A course as stored on the user's profile. Extends CatalogEntry with a
 * `source` tag: "verified" (from the catalog) or "manual" (self-reported).
 */
export type UserCourse = CatalogEntry & {
  source: "verified" | "manual";
};

export type MockAttempt = {
  id: string;
  courseCode: string;
  courseTitle: string;
  score: number; // 0..100
  correct: number;
  total: number;
  submittedAt: number;
  topics: { topic: string; score: number }[];
  /** Exact questions asked, in presentation order (for the review screen). */
  questions?: AIQuestion[];
  /** The student's selected option index per question, aligned with `questions`. */
  answers?: (number | null)[];
  /** Settings used, so "Retake This Test" can regenerate with the same setup. */
  settings?: CourseTestSettings;
};


export type InProgressTest = {
  courseCode: string;
  courseTitle: string;
  questionCount: number;
  durationSec: number;
  startedAt: number;
  answers: (number | null)[];
  currentIndex: number;
  questionIds: number[];
  /** "ai" = questions live in profile.aiQuestions; "sample" = built-in bank. */
  source?: "ai" | "sample";
} | null;

export type TopicScore = { course: string; topic: string; score: number };

export type Difficulty = "gentle" | "balanced" | "challenging" | "exam";

export type CourseTestSettings = {
  questionCount: number;
  minutes: number;
  difficulty: Difficulty;
  topicFocus: string[];
};

/** A question generated by the AI backend. */
export type AIQuestion = {
  id: number;
  topic: string;
  question: string;
  options: string[];
  correct_index: number;
  explanation: string;
};

/** Stored result of a real "Analyze Upload" run, keyed by course code. */
export type CourseTopicAnalysis = {
  materialId: string;
  analyzedAt: number;
  topics: { topic: string; confidence: number }[];
};

/* ---------- View router ---------- */

export type OnboardingStep =
  | "splash"
  | "disclaimer"
  | "disclaimer-blocked"
  | "identity"
  | "goal"
  | "timeline"
  | "study-pref"
  | "faculty"
  | "department"
  | "level"
  | "courses";

export type Goal = "pass" | "top-grades" | "catch-up";
export type Timeline = "lt-week" | "2-4-weeks" | "gt-month" | "unsure";
export type StudyPreference = "practice" | "flashcards" | "reading";

export type LocalAccount = { name: string; email: string; password: string };

export type AppView =
  | "dashboard"
  | "course-detail"
  | "mock-gen"
  | "mock-config"
  | "mock-run"
  | "mock-result"
  | "settings"
  | "flashcards-soon"
  | "add-course"
  | "all-uploads"
  | "attempt-review"
  | "cgpa";

/* ---------- CGPA calculator + static study plan ---------- */

export type CgpaInputs = {
  currentCgpa: string;
  currentUnits: string;
  targetCgpa: string;
  daysRemaining: string;
  /** course code -> credit units for this semester */
  units: Record<string, number>;
};

export type CgpaPlanCourse = {
  code: string;
  name: string;
  units: number;
  requiredPoints: number;
  requiredGrade: string;
  requiredPercent: string;
  highImpact: boolean;
  dailyReadingMinutes: number;
  dailyMockQuestions: number;
};

export type CgpaPlan = {
  createdAt: number;
  currentCgpa: number;
  currentUnits: number;
  targetCgpa: number;
  daysRemaining: number;
  semesterUnits: number;
  /** Semester GPA needed across this semester's units to hit the target. */
  requiredSemesterGpa: number;
  reachable: boolean;
  alreadyThere: boolean;
  targetClassification: string;
  probationNote: boolean;
  courses: CgpaPlanCourse[];
};




/* ---------- Profile ---------- */

export type Profile = {
  identity: { kind: "email" | "guest"; name: string; email?: string } | null;
  accounts: LocalAccount[];
  disclaimerAccepted: boolean;
  goal: Goal | null;
  timeline: Timeline | null;
  studyPreference: StudyPreference | null;
  faculty: string | null;
  department: string | null;
  level: Level | null;
  courses: UserCourse[];
  setupComplete: boolean;

  // Mock test state
  attempts: MockAttempt[];
  topicScores: TopicScore[];
  inProgressTest: InProgressTest;
  lastResultId: string | null;

  // Streak
  streakDays: number;
  lastQualifyingDay: string | null; // YYYY-MM-DD

  // Milestones (one-time celebrations)
  hasCompletedFirstMock: boolean;
  masteredCourses: string[]; // course codes that have crossed 70% average once

  // Per-course last-used mock test settings
  courseTestSettings: Record<string, CourseTestSettings>;

  // Real AI-generated question set backing the current/last mock test
  aiQuestions: AIQuestion[];

  // Real topic analysis per course code (from "Analyze Upload")
  courseTopicAnalysis: Record<string, CourseTopicAnalysis>;
};

const emptyProfile: Profile = {
  identity: null,
  accounts: [],
  disclaimerAccepted: false,
  goal: null,
  timeline: null,
  studyPreference: null,
  faculty: null,
  department: null,
  level: null,
  courses: [],
  setupComplete: false,
  attempts: [],
  topicScores: [],
  inProgressTest: null,
  lastResultId: null,
  streakDays: 0,
  lastQualifyingDay: null,
  hasCompletedFirstMock: false,
  masteredCourses: [],
  courseTestSettings: {},
  aiQuestions: [],
  courseTopicAnalysis: {},
};

type Ctx = {
  profile: Profile;
  step: OnboardingStep | "dashboard";
  view: AppView;
  activeCourseCode: string | null;
  activeAttemptId: string | null;
  update: (p: Partial<Profile>) => void;
  go: (s: OnboardingStep | "dashboard") => void;
  navigate: (v: AppView, opts?: { courseCode?: string | null; attemptId?: string | null }) => void;
  resetSetup: () => void;
};

const StoreCtx = createContext<Ctx | null>(null);
const KEY = "truefluency-profile-v2";

export function ProfileProvider({ children }: { children: ReactNode }) {
  const [profile, setProfile] = useState<Profile>(emptyProfile);
  const [step, setStep] = useState<OnboardingStep | "dashboard">("splash");
  const [view, setView] = useState<AppView>("dashboard");
  const [activeCourseCode, setActiveCourseCode] = useState<string | null>(null);
  const [activeAttemptId, setActiveAttemptId] = useState<string | null>(null);
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem(KEY);
      if (raw) {
        const parsed = JSON.parse(raw) as Profile;
        setProfile({ ...emptyProfile, ...parsed });
        if (parsed.setupComplete) setStep("dashboard");
      }
    } catch { /* ignore */ }
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (hydrated) {
      try { localStorage.setItem(KEY, JSON.stringify(profile)); } catch { /* ignore */ }
    }
  }, [profile, hydrated]);

  const update = (p: Partial<Profile>) => setProfile((cur) => ({ ...cur, ...p }));
  const go = (s: OnboardingStep | "dashboard") => {
    setStep(s);
    if (s === "dashboard") setView("dashboard");
  };
  const navigate = (v: AppView, opts?: { courseCode?: string | null; attemptId?: string | null }) => {
    setView(v);
    if (opts && "courseCode" in opts) setActiveCourseCode(opts.courseCode ?? null);
    if (opts && "attemptId" in opts) setActiveAttemptId(opts.attemptId ?? null);
  };
  const resetSetup = () => {
    setProfile(emptyProfile);
    setStep("splash");
    setView("dashboard");
    setActiveCourseCode(null);
    setActiveAttemptId(null);
    try { localStorage.removeItem(KEY); } catch { /* ignore */ }
  };

  return (
    <StoreCtx.Provider value={{ profile, step, view, activeCourseCode, activeAttemptId, update, go, navigate, resetSetup }}>
      {hydrated ? children : null}
    </StoreCtx.Provider>

  );
}

export function useProfile() {
  const ctx = useContext(StoreCtx);
  if (!ctx) throw new Error("useProfile must be used inside ProfileProvider");
  return ctx;
}

/* ---------- Streak + milestone helpers ---------- */

function today(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function yesterday(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

/**
 * Update the streak after a qualifying activity (currently: mock test completion).
 * Structured so flashcards etc. can call this later without a rewrite.
 */
export function bumpStreak(p: Profile): Pick<Profile, "streakDays" | "lastQualifyingDay"> {
  const t = today();
  if (p.lastQualifyingDay === t) {
    return { streakDays: p.streakDays, lastQualifyingDay: t };
  }
  if (p.lastQualifyingDay === yesterday()) {
    return { streakDays: p.streakDays + 1, lastQualifyingDay: t };
  }
  return { streakDays: 1, lastQualifyingDay: t };
}

export function hasQualifyingActivityToday(p: Profile): boolean {
  return p.lastQualifyingDay === today();
}

export function averageForCourse(p: Profile, code: string): number | null {
  const rel = p.attempts.filter((a) => a.courseCode === code);
  if (!rel.length) return null;
  return Math.round(rel.reduce((s, a) => s + a.score, 0) / rel.length);
}
